'\" t
.\"     Title: ssock_get_fd
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 27/04/2015
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: Spanish
.\"
.TH "SSOCK_GET_FD" "3" "27/04/2015" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOMBRE"
*ssock_get_fd* \- Devuelve el descriptor de fichero del SSock
.SH "SYNOPSIS"
.sp
\fB#include <G\-2301\-05\-P3\-ssock\&.h>\fR
.sp
\fIint\fR \fBssock_get_fd\fR(\fISSock* ss\fR);
.SH "DESCRIPTION"
.sp
Devuelve el numero asociado al SSock \fIss\fR proporcionado\&. Esta funcion debe usarse con precaucion, puesto que puede haber un objeto SSL por encima del descriptor que haga asunciones sobre el socket\&.
.SH "RETURN VALUE"
.PP
\fB>0\fR
.RS 4
El descriptor de fichero\&.
.RE
.PP
\fBERR\fR
.RS 4
Ha ocurrido un error (argumento erroneo)\&.
.RE
.SH "SEE ALSO"
.sp
ssock_new(3), ssock_secure_new(3)
.SH "AUTHORS"
.sp
Ana Alonso <ana\&.alonsoa@estudiante\&.uam\&.es>, Manuel Blanc <manuel\&.blanc@estudiante\&.uam\&.es>
