#!/bin/sh

HOST=localhost
PORT=${1:-4433}

CERT=client.pem
KEY=client.key
ROOT=root.pem

echo "openssl s_client -cert "$KEY" -key "$KEY" -CAfile "$ROOT" -connect "$HOST:$PORT""
openssl s_client -cert "$KEY" -key "$KEY" -CAfile "$ROOT" -connect "$HOST:$PORT"