#!/bin/sh

HOST=localhost
PORT=${1:-4433}

CERT=cert/manu.pem
KEY=cert/manu.key
ROOT=cert/root.pem

echo "openssl s_client -cert $CERT -key $KEY -CAfile $ROOT -connect $HOST:$PORT"
openssl s_client -cert "$CERT" -key "$KEY" -CAfile "$ROOT" -connect "$HOST:$PORT"