#!/bin/sh

HOST=localhost
PORT=${1:-4433}

CERT=../cert/client.pem
KEY=../cert/client.key
ROOT=../cert/root.pem

openssl s_client -crlf -cert "$CERT" -key "$KEY" -CAfile "$ROOT" -connect "$HOST:$PORT"
